- name: Operating System Bootstrap
  hosts: localhost
  connection: local

  vars:
    - os: macos

  pre_tasks:
    - name: Upgrade
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

  tasks:
    - name: Install brew packages.
      community.general.homebrew:
        name:
          # General
          - htop
          - jq
          - ipcalc
          - fish
          - kubectl
          - helm
          - asdf

    - name: Install brew cask packages.
      community.general.homebrew_cask:
        name:
          - google-cloud-sdk
          - clipy
          - docker

    - name: Install brew cask packages.
      community.general.homebrew_cask:
        name:
          - google-cloud-sdk
          - clipy

    - name: Ensure fish added to allowed shells.
      lineinfile:
        path: /etc/shells
        regexp: ".*fish$"
        line: /opt/homebrew/bin/fish
      become: true

    - include_tasks: ./tasks/install-asdf-plugins.yaml
      with_items:
        - path: plugins/golang/README.md
          cmd: "asdf plugin-add golang https://github.com/kennyp/asdf-golang.git"
        - path: plugins/nodejs/README.md
          cmd: "asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git"
        - path: plugins/python/README.md
          cmd: "asdf plugin-add python"
        

    # TODO: Duplicated in main
    - include_tasks: ./tasks/install-fish-addons.yaml
      with_items:
        - path: completions/fisher.fish # Fisher must be the first item.
          cmd: "curl -sL https://git.io/fisher | source - && fisher install jorgebucaran/fisher"
        - path: completions/gcloud.fish
          cmd: "fisher install aliz-ai/google-cloud-sdk-fish-completion"
        - path: completions/kubectl.fish
          cmd: "fisher install evanlucas/fish-kubectl-completions"
        - path: completions/nvm.fish
          cmd: "fisher install jorgebucaran/nvm.fish"
        - path: functions/bass.fish
          cmd: "fisher install edc/bass"
        - path: completions/asdf.fish
          cmd: "fisher install rstacruz/fish-asdf"

    - name: Copy config.fish.
      copy:
        src: ./config.mac.fish # Use config.fish and fill differences with jinja template
        dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"
