- name: Operating System Bootstrap
  hosts: localhost
  connection: local

  pre_tasks:
    
    - name: Update apt cache if it's needed.
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 3600
      become: true

  tasks:

    - name: Install prerequisite apt packages.
      apt:
        name:
          - git
          - curl
          - apt-transport-https
          - gnupg
          - ca-certificates
          - python3-pip
          - software-properties-common
          - bison


    - name: Import the 3rd party apt packages GPG keys.
      apt_key:
        url: "{{ item }}"
        state: present
      with_items:
          - https://baltocdn.com/helm/signing.asc
          - https://apt.releases.hashicorp.com/gpg
          - https://download.docker.com/linux/ubuntu/gpg
          - https://ngrok-agent.s3.amazonaws.com/ngrok.asc
          - https://www.virtualbox.org/download/oracle_vbox_2016.asc 
          - https://www.virtualbox.org/download/oracle_vbox.asc 
      become: true

    - name: Import the 3rd party apt packages GPG keys. (trusted-gpg)
      apt_key:
        url: "{{ item.url }}"
        keyring: "{{ item.keyring }}"
        state: present
      with_items:
        - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          keyring: /etc/apt/trusted.gpg.d/cloud.google.gpg
        - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          keyring: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
      become: true

    - name: Add the 3rd party apt packages repositories.
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
        filename: "{{ item.file_name }}"
        update_cache: true
      with_items:
        - repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main'
          file_name: google-cloud-sdk
        - repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
          file_name: kubernetes
        - repo: 'deb https://baltocdn.com/helm/stable/debian/ all main'
          file_name: helm-stable-debian
        - repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com xenial main'
          file_name: hashicorp
        - repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
          file_name: docker
        - repo: 'deb https://ngrok-agent.s3.amazonaws.com buster main'
          file_name: ngrok
        - repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian buster contrib'
          file_name: virtualbox
      become: true

    - name: Install apt packages.
      apt:
        name:
          # General
          - htop
          - curl
          - unrar
          - ipcalc
          # GUI
          - parcellite
          # 3rd party
          - google-cloud-sdk
          - kubectl
          - helm
          - terraform
          - vagrant
          - docker-ce
          - ngrok
          - virtualbox
        state: present
      become: true

    - name: Install Snap packages.
      snap:
        name: 
          - brave
          - skype
          - bitwarden
      become: true

    - name: Install Snap packages. (classic)
      snap:
        name: 
          - code
        classic: true
      become: true
