---
- name: "Install asdf plugin ({{ item.path }})."
  shell: "{{ item.cmd }}"
  args:
    executable: "{{ (os == 'macos') | ternary('/opt/homebrew/bin/fish', '/usr/bin/fish') }}"
    creates: "{{ ansible_env.HOME }}/.asdf/{{ item.path }}"
